/**
 * Official TrueRTE React component
 * Copyright (c) 2026 TrueRTE contributors
 * Licensed under the MIT license (https://github.com/truerte/truerte-react/blob/main/LICENSE.TXT)
 */

export const nativeEvents = [
  'BeforePaste',
  'Blur',
  'Click',
  'CompositionEnd',
  'CompositionStart',
  'CompositionUpdate',
  'ContextMenu',
  'Copy',
  'Cut',
  'Dblclick',
  'Drag',
  'DragDrop',
  'DragEnd',
  'DragGesture',
  'DragOver',
  'Drop',
  'Focus',
  'FocusIn',
  'FocusOut',
  'Input',
  'KeyDown',
  'KeyPress',
  'KeyUp',
  'MouseDown',
  'MouseEnter',
  'MouseLeave',
  'MouseMove',
  'MouseOut',
  'MouseOver',
  'MouseUp',
  'Paste',
  'SelectionChange',
] as const;

export const customEvents = [
  'Activate',
  'AddUndo',
  'BeforeAddUndo',
  'BeforeExecCommand',
  'BeforeGetContent',
  'BeforeRenderUI',
  'BeforeSetContent',
  'Change',
  'ClearUndos',
  'CommentChange',
  'Deactivate',
  'Dirty',
  'ExecCommand',
  'GetContent',
  'Hide',
  'IconsLoadError',
  'Init',
  'LanguageLoadError',
  'LoadContent',
  'ModelLoadError',
  'NodeChange',
  'ObjectResizeStart',
  'ObjectResized',
  'ObjectSelected',
  'PluginLoadError',
  'PostProcess',
  'PostRender',
  'PreProcess',
  'ProgressState',
  'Redo',
  'Remove',
  'Reset',
  'ResizeEditor',
  'SaveContent',
  'SetAttrib',
  'SetContent',
  'Show',
  'SkinLoadError',
  'Submit',
  'ThemeLoadError',
  'Undo',
  'VisualAid',
] as const;

export const validEvents = [ ...nativeEvents, ...customEvents ] as const;
